### PR TITLE
Refactor workflow as code

### PR DESCRIPTION
**Pull request by gardusig**

### CODE REVIEW

**Comment by maxwell201819** [comment]
"Hi Gardusig, I also need this feature now. May I ask why you closed it?"

**Comment by gardusig** [comment]
Hi @maxwell201819, I had left the company who manages it and thought that it was better to close. Please let me know if I can help anyhow :)

**Comment by maxwell201819** [comment]
Hi  Gustavo, thank you very much for your response. I really need the code logic to parse the JSON file defining the workflow as mentioned above. Is there a way to submit it?

**Comment by gardusig** [comment]
I think you should create an issue with a feature request while adding some description. Even if I send a PR, there is no guarantee it will be approved/merged into the codebase. You can ask for the team (e.g. @v1r3n or @coderabhigupta) to take a look at it.

**Pull request closed without merging**
